Fix: Replace cleanup_app with cleanup in main.c
BUGFIX:
- Fixed undefined reference to cleanup_app()
- Should be cleanup() as defined in app_common.h
- Build now succeeds

This was a simple typo that caused linking error.